file = open('toutiao_cat_data.txt', 'a+')
for i in range(100):
    file.write('今天晚上有好看的电影\n')
    file.write('北京奥运会开幕式非常精彩\n')
    file.write('金庸的武侠小说非常精彩\n')
    file.write('深度学习技术\n')
    file.write('人工智能的发展\n')
    file.write('在天安门广场举行了隆重的阅兵式\n')
    file.write('具有良好的沟通能力和交流能力\n')
    file.write('人在阅读时是从左到右逐字读入的\n')
    file.write('减少课程的课时是十分科学的\n')
    file.write('请大家选择你觉得可以的时间\n')
    file.write('头昏眼花\n')
    file.write('失信被执行人\n')
    file.write('夫妻本是同林鸟\n')
    file.write('四大名著\n')
    file.write('我戴着一副黑框眼镜\n')
    file.write('他钢琴弹得不错\n')
    file.write('小朋友们都喜欢去郊游\n')
    file.write('这个玩具很有趣\n')
    file.write('他很生气\n')
    file.write('今天天气很好\n')
    file.write('我们去散步吧\n')
    file.write('大家可能不知道\n')
    file.write('我们宿舍的灯坏了\n')
file.close()